namespace:
  name: staging

service:
  port: 5000

image:
  tag: '3.0'
  pullPolicy: Always

replicaCount: 3

resources:
  requests:
    cpu: 300m
    memory: 90Mi
  limits:
    cpu: 500m
    memory: 128Mi
ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod-argocd"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - hello-k8s.vuihoctech.com
    secretName: hello-k8s-tls
  rules:
    - host: hello-k8s.vuihoctech.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: hello-k8s
                port:
                  number: 5000
